
title: CV - MJGS
url: 'https://miwe77.github.io'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Miguel Jesús García Sánchez  ## put your name
title: 'SYSADMIN CONSULTANT'  ## your title
location: Jaén , Spain


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
